rozhen/urls.py
from django.urls import path
from rozhen import views

app_name = 'rozhen'

urlpatterns = [
    path('', views.index, name='index'),
    path('base/', views.base, name='base'),
]

solarweb/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rozhen import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('rozhen/', include('rozhen.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rozhen/models.py
from django.db import models

# Create your models here.

rozhen/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    # Construct a dictionary to pass to the template engine as its context.
    # Note the key boldmessage matches to {{ boldmessage }} in the template!
    context_dict = {}
    # Return a rendered response to send to the client.
    # We make use of the shortcut function to make our lives easier.
    # Note that the first parameter is the template we wish to use.
    return render(request, 'rozhen/index.html', context=context_dict)
    
def base(request):
    # Construct a dictionary to pass to the template engine as its context.
    # Note the key boldmessage matches to {{ boldmessage }} in the template!
    context_dict = {}
    # Return a rendered response to send to the client.
    # We make use of the shortcut function to make our lives easier.
    # Note that the first parameter is the template we wish to use.
    return render(request, 'rozhen/base.html', context=context_dict)


templates/rozhen/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Base template</title>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400&display=swap" rel="stylesheet">
        <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
		
        <title>
            Rate my CS course -
            {% block title_block %}
            A WAD2 Group Project
            {% endblock %}
        </title>
    </head>
	
	<body>
        <!--Navigation-->
        <div class="wrapper">
            <nav class="navbar navbar-expand-lg navbar-dark bg-transparent w-100">
                <div class="d-flex flex-grow-1">
                    <span class="w-100 d-lg-none d-block"><!-- hidden spacer to center brand on mobile --></span>
                    <a href="" class="navbar-brand d-none d-lg-inline-block" >
                        <img src="{% static 'images/logoTransp.png' %}" alt="Logo">
                    </a>
                    <a href="#" class="navbar-brand-two mx-auto d-lg-none d-inline-block" >
                        <img src="{% static 'images/logoTransp.png' %}" alt="Logo">
                    </a>
                    <div class="w-100 text-right">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#myNavbar">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                    </div>
                </div>
                <div class="collapse navbar-collapse flex-grow-1 text-right" id="myNavbar">
                    <ul class="navbar-nav ml-auto flex-nowrap">
                        <li class="nav-item">
                            <a href="" class="nav-link m-2 menu-item nav-active" >Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link m-2 menu-item">News</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle m-2 menu-item" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Instruments
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'rozhen:base' %}">15cm Coronagraph</a>
                                <a class="dropdown-item" href="">30cm Chromosphere Telescope</a>
                                <a class="dropdown-item" href="">Cameras</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle m-2 menu-item" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Research
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="">Projects</a>
                                <a class="dropdown-item" href="">Publications</a>
                                <a class="dropdown-item" href="">Presentations</a>
                                <a class="dropdown-item" href="">Data Archive</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle m-2 menu-item" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Education
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="">Gallery</a>
                                <a class="dropdown-item" href="">Popular presentations</a>
                                <a class="dropdown-item" href="">Education</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle m-2 menu-item" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Contact
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="">Staff</a>
                                <a class="dropdown-item" href="">Address</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
            
        </div>
        
        <main>
            {% block body_block %}
            {% endblock %}
        </main>
        <footer>
            <div class="container padding">
                <div class="row padding">
                    <div class="col-xs-12 col-sm-6 col-md-4 text-center">
                        <div id="map">
                            <iframe width='100%' height='100%' id='mapcanvas' src='https://maps.google.com/maps?q=Bulgarian%20National%20Astronomical%20Observatory&amp;t=&amp;z=11&amp;ie=UTF8&amp;iwloc=&amp;output=embed' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'><div class="zxos8_gm">Not sure if you have <a href="https://www.vouchersort.co.uk/hush-uk.com">found it but hotukdeals</a> is sometimes not the best place</div><div style='overflow:hidden;'><div id='gmap_canvas' style='height:100%;width:100%;'></div></div><div><small>Powered by <a href="https://www.embedgooglemap.co.uk">Embed Google Map</a></small></div></iframe>
                        </div>
                        
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-4 text-left pt-1">
                        <a href="#"><img src="{% static 'images/logoTransp.png' %}" alt="Logo"></a>
                        <h5>Solar Observations in Bulgaria</h5>
                        <hr>
                        <h5>Address 1</h5>
                        <p>NAO Rozhen</p>
                        <p>PO Box 136</p>
                        <p>4700 Smolyan</p>
                        <p>Bulgaria</p>
                        <h6>Phone: <a id="phone" href="tel:+359 879 603456">+359 879 603456</a></h6>
                    </div>
                    <div class="col-sm-12 col-md-4 text-right pt-3">
                        <h5>Address 2</h5>
                        <p>72 Tsarigradsko Chaussee Blvd.</p>
                        <p>1784 Sofia</p>
                        <p>Bulgaria</p>
                        <p>Email: <a id="phone" href="mailto:office@astro.bas.b">office@astro.bas.b</a></p>
                        <h6>Phone: <a id="phone" href="tel:+359 2 9741910">+359 2 9741910</a></h6>
                        <hr>
                        <a href="http://nao-rozhen.org/"><img id="NAO" src="{% static 'images/nao.png' %}" width="100" height="58" alt="NAO Rozhen"></a>
                        <a href="http://www.bas.bg/"><img id="BAN" src="{% static 'images/ban.png' %}" width="105" height="57" alt="BAS Bulgaria"></a>   
                    </div>
                </div>
            </div>
        </footer>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.2.6/gsap.min.js"></script>  
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="{% static 'js/index.js' %}"></script>
    </body>
    
</html>